[package]
name = "lottery"
version = "0.1.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
lottery = "CsgojSEAWiq9Ns1hW2Y8mmvKVhcmF9vU5W6fUXjg4uDi"

[programs.localnet]
lottery = "CsgojSEAWiq9Ns1hW2Y8mmvKVhcmF9vU5W6fUXjg4uDi"

[programs.mainnet]
lottery = "CsgojSEAWiq9Ns1hW2Y8mmvKVhcmF9vU5W6fUXjg4uDi"

[registry]
url = "https://github.com/zohu/csgohome"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"